name: Phasecurve Technologies Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello Phasecurve Technologies
        run: echo "Phasecurve Technologies"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye Phasecurve Technologies
        run: echo "Goodbye Phasecurve Technologies"
        shell: bash
