name: Phasecureve Technologies Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello Phasecureve Technologies
        run: echo "Phasecureve Technologies"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye Phasecureve Technologies
        run: echo "Goodbye Phasecureve Technologies"
        shell: bash
